<?php

namespace Tests;

use Illuminate\Foundation\Testing\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->withoutExceptionHandling();
    }

    protected function signIn($user = null)
    {
        $user = is_null($user) ? create('App\User') : $user;
        $this->actingAs($user);
        return $this;
    }

}
